################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates.
# Fiserv is a trademark of Fiserv, Inc.,
# registered or used in the United States and foreign countries,
# and may or may not be registered in your country.
# All trademarks, service marks,
# and trade names referenced in this
# material are the property of their
# respective owners. This work, including its contents
# and programming, is confidential and its use
# is strictly limited. This work is furnished only
# for use by duly authorized licensees of Fiserv, Inc.
# or its affiliates, and their designated agents
# or employees responsible for installation or
# operation of the products. Any other use,
# duplication, or dissemination without the
# prior written consent of Fiserv, Inc.
# or its affiliates is strictly prohibited.
# Except as specified by the agreement under
# which the materials are furnished, Fiserv, Inc.
# and its affiliates do not accept any liabilities
# with respect to the information contained herein
# and are not responsible for any direct, indirect,
# special, consequential or exemplary damages
# resulting from the use of this information.
# No warranties, either express or implied,
# are granted or extended by this work or
# the delivery of this work
################################################################################

- sections:
  - title: Introduction
    link: docs/introduction/introduction.md
  - title: Frequently Asked Questions
    link: docs/faq/faq.md
  - title: Request a Sandbox
    link: docs/sandbox/request.md
  - title: Interactive guide
    link: docs/interactive-guide/interactive-guide.md
    sections:
    - title: API Flow
      link: docs/interactive-guide/api-flow/apiflow.md
      sections:
      - title: Recipient Profiles
        link: docs/interactive-guide/api-flow/create-recipient.md
        sections:
        - title: Create Recipient
          link: docs/interactive-guide/api-flow/create-recipient.md
        - title: Update Recipient
          link: docs/interactive-guide/api-flow/update-recipient.md
        - title: Get Recipient
          link: docs/interactive-guide/api-flow/retrieve-recipient.md
      - title: How to Rerieve Encryption Key
        link: docs/interactive-guide/api-flow/create-public-token.md
      - title: How to Rerieve Single Use Token
        link: docs/interactive-guide/api-flow/create-nonce-token.md
      - title: How to Save Payment Method (Acount Vaulting)
        link: docs/interactive-guide/api-flow/vault-payent.md
      - title: How to Initiate, Cancel, and View Transactions
        sections:
        - title: How to initiate a Transaction.
          link: docs/interactive-guide/api-flow/create-disbursement.md
        - title: How to view a Transaction.
          link: docs/interactive-guide/api-flow/get-transaction-details.md
        - title: How to Cancel a Transaction.
          link: docs/interactive-guide/api-flow/cancel-payment.md
    - title: PORTAL Flow
      sections:
      - title: How to Initiate Single Consumer Payment
        link: docs/interactive-guide/portal-flow/singleConsumerflow.md
      - title: How to Initiate Multi Consumer Payment
        link: docs/interactive-guide/portal-flow/multiConsumerflow.md
      - title: How to Initiate Single Company Payment
        link: docs/interactive-guide/portal-flow/singleCompanyflow.md
      - title: How to Initiate Multi Company Payment
        link: docs/interactive-guide/portal-flow/multiCompanyflow.md
    - title: BATCH Flow
      sections:
      - title: BATCH File
        link: docs/interactive-guide/batch-flow/batchflow.md
        
