################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: DigitalDisbursements
  productionDescription: REPLACEME
  whoIsItFor: REPLACEME
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: DigitalDisbursements™
featuredFeatures:
  - title: Recipient Portal
    description:  DigitalDisbursements solution allows financial Institution to issue and manage the Credit Card products to their end customers via an easy to use and integrate Customer Portal
    tags: ["APAC", "FirstVision", "Credit"]
    bullets: ["Activate Card", "Block Card", "Lost Stolen Card Transfer", "CVV2 Validation" ]
    relatedDocs:
      - relatedDoc: 
        title: Interactive Guide
        description: Gives an easy to follow walk through of how integrate the Recipient Protal.
        link: .docs/interactive-guide/portal-flow/singleConsumerflow.md
      - relatedDoc: 
        title: Portal Demo <Needs link>
        description: Gives a walk through of the customer experiance using the Recipient Protal. 
        link: 
      - relatedDoc: 
        title: Sending Payments to multiple recipients.
        description: Allows management of payment instrument that is used to perform financial transaction.  Example physical Card, Virtual Card, Wallet Token. 
        link: ./docs/Card-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Create and Initiate payment.
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "../api/?type=post&path=/ddp/v1/payments"
  - title: Hosted Pages
    description:  Digital Disbursements solution allows financial Institution to embed the customer portal into their existing website.
    tags: ["APAC", "FirstVision", "Credit"]
    bullets: ["Activate Card", "Block Card", "Lost Stolen Card Transfer", "CVV2 Validation" ]
    relatedDocs:
      - relatedDoc: 
        title: Interactive Guide
        description: Gives an easy to follow walk through of how integrate hosted pages in your application.
        link: .docs/interactive-guide/portal-flow/singleConsumerflow.md
      - relatedDoc: 
        title: Hasted Pages Demo <Needs link>
        description: Gives a walk through of the customer experiance using the Recipient Protal. 
        link: 
      - relatedDoc: 
        title: FAQs
        description: Source to refrence frequently asked questions about digital dibursements.
        link: ./docs/Card-Management.md
