################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: DigitalDisbursements
  productionDescription: The Digital Disbursements Platform (DDP) is a cloud-based solution that digitizes the payouts process for both businesses and consumers alike. Through simple API integration, DDP allows merchants to issue single or bulk payouts to consumers and/or businesses in a secure, timely and cost-effective manner. For the recipient, the platform provides access to a variety of payout methods that allows choice of accepting their money when and how they prefer
  whoIsItFor: Who is it for?
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: DigitalDisbursements™
featuredFeatures:
  - title: Operational Efficiency 
    description:  Digital Disbursements offers operational efficiency by simplifying operations and reducing resource demand across treasury, accounting, technical, and support teams. Our single client portal provides settlement, reconciliation, and reporting for all your payout capabilities, streamlining your operations and enabling you to allocate resources more efficiently.
    relatedDocs:
      - relatedDoc: 
        title: Portal Flow
        description: Learn how to integrate with our recipient portal for a great user Experience and Low integration cost.
        link: /docs/interactive-guide/portalflow.md
      - relatedDoc: 
        title: FAQs
        description: Take a look at our FAQa. 
        link: docs/faq/faq.md
    relatedAPIs:
      - relatedAPI: 
        title: Create and Pay
        description: create and send a payment with this single API endpoint.
        type: "POST"        
        path: /ddp/v1/payments&version=1.0.0
  - title: Built-in Security
    description:  Digital Disbursements provides built-in security features such as fraud prevention, tokenization, and optimization that reduce risk and ensure high approval rates. By leveraging our value-added services, businesses can eliminate the PCI burden, secure payment credentials, and achieve the highest approval rates.
    relatedDocs:
      - relatedDoc: 
        title: FAQs
        description: Take a look at our FAQa. 
        link: docs/faq/faq.md
  - title: Recipient benefits
    description:  Digital Disbursements provides recipients with access to a variety of payout methods, allowing them to choose their preferred method of receiving funds. Recipients can easily select payment preferences, with the ability to split single payouts to multiple endpoints, and can complete payouts in "guest mode" for added convenience.
    relatedDocs:
      - relatedDoc: 
        title: Create a Payment
        description: Here you will find a list of each available payment method.
        link: docs/interactive-guide/apiflow.md#step-3-create-a-payment
      - relatedDoc: 
        title: FAQs
        description: Take a look at our FAQa. 
        link: docs/faq/faq.md
    relatedAPIs:
      - relatedAPI: 
        title: Disburse a Payment
        description: Use this API to send payments in as little as 5 seconds!
        type: "patch"        
        path: /ddp/v1/payments/{id}/disburse&version=1.0.0
