################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: DigitalDisbursements
  productionDescription: The Digital Disbursements Platform (DDP) is a cloud-based solution that digitizes the payouts process for both businesses and consumers alike. Through simple API integration, DDP allows merchants to issue single or bulk payouts to consumers and/or businesses in a secure, timely and cost-effective manner. For the recipient, the platform provides access to a variety of payout methods that allows choice of accepting their money when and how they prefer
  whoIsItFor: Who is it for?
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: DigitalDisbursements™
featuredFeatures:
  - title: Operational Efficiency 
    description:  Description
    tags: ["APAC", "FirstVision", "Credit"]
    bullets: ["Activate Card", "Block Card", "Lost Stolen Card Transfer", "CVV2 Validation" ]
    relatedDocs:
      - relatedDoc: 
        title: REPLACE ME WITH DOC
        description: Description
        link: 
      - relatedDoc: 
        title: REPLACE ME WITH DOC
        description: Description. 
        link: 
      - relatedDoc: 
        title: REPLACE ME WITH DOC
        description: Description
        link: 
    relatedAPIs:
      - relatedAPI: 
        title: REPLACE ME WITH API LINK
        description: Description
        type: "patch"        
        path: "../api/?type=post&path=/ddp/v1/payments"
  - title: Built-in Security
    description:  Description
    tags: ["APAC", "FirstVision", "Credit"]
    bullets: ["Activate Card", "Block Card", "Lost Stolen Card Transfer", "CVV2 Validation" ]
    relatedDocs:
      - relatedDoc: 
        title: REPLACE ME WITH DOC
        description: Description
        link:
      - relatedDoc: 
        title: REPLACE ME WITH DOC
        description: Description
      - relatedDoc: 
        title: REPLACE ME WITH DOC
        description: Description
        link:
    relatedAPIs:
      - relatedAPI: 
        title: REPLACE ME WITH API LINK
        description: Description
        type: "patch"        
        path: "../api/?type=post&path=/ddp/v1/payments"
  - title: Recipient benefits
    description:  Description
    tags: ["APAC", "FirstVision", "Credit"]
    bullets: ["Activate Card", "Block Card", "Lost Stolen Card Transfer", "CVV2 Validation" ]
    relatedDocs:
      - relatedDoc: 
        title: REPLACE ME WITH DOC
        description: Description
        link:
      - relatedDoc: 
        title: REPLACE ME WITH DOC
        description: Description
      - relatedDoc: 
        title: REPLACE ME WITH DOC
        description: Description
        link:
    relatedAPIs:
      - relatedAPI: 
        title: REPLACE ME WITH API LINK
        description: Description
        type: "patch"        
        path: "../api/?type=post&path=/ddp/v1/payments"
